export enum ActionStatusEnum {
            Open= 1,
            DirectClose= 1,
            Reply= 2,
            ReplyAndClose= 3,
            Escalate= 4,
            ReplyAndEscalate= 5,
            CreateTicket= 6,
            Approve= 7,
            Reject= 8,
            AttachTicket= 9,
            EscalateToBrand= 10,
            BrandApproved= 11,
            BrandReject= 12,
            ReplyAndOnHold= 13,
            ReplyAndAwaitingCustomerResponse= 14,
            ReplyNewMentionCameAfterEsalatedorOnHold= 15,
            Acknowledge= 16
}
export enum ClientStatusEnum {
            MarkActionable= 18,
            SRCreated= 20,
            Closed= 4,
            RepliedToUser= 3,
            Escalated= 25,
            MarkedForAutoclosure= 38,
            ReopenACase= 13,
            CaseCreated= 10,
            CaseAttach= 29,
            CaseDetach= 30,
            Ignore= 5,
            Approve= 8,
            ModifyCategoryInformation= 36,
            EmailSent= 46,
            PriorityChanged= 39,
            Assigned= 42,
            Unassigned= 44,
            NotesAdded= 45,
            FeedbackSent= 47,
            OnHold= 35,
            CustomerInfoAwaited= 48,
            NewMentionCameAfterEsalatedorOnHold= 49,
            Acknowledge= 50,  // This Status is only to identify log status in table will be 49
            SRUpdated= 51,
            SRClosed= 52,
            CopyMentionFrom= 53,
            CopyMentionTo= 54,
            MoveMentionTo= 55,
            MoveMentionFrom= 56,
            EmailForward= 57,
            ReplySentForApproval= 58,
            ReplyRejected= 59,
            ReplyTextModified= 60,
            ReplyApproved= 61,
            ReplyScheduled= 62
}

