export enum ChannelImage {
    Twitter = '/assets/images/channel-logos/twitter.svg',
    Facebook = '/assets/images/channel-logos/facebook.svg',
    Instagram = '/assets/images/channel-logos/instagram.svg',
    Youtube = '/assets/images/channelicons/Youtube.svg',
    LinkedIn = '/assets/images/channel-logos/linkedin.svg',
    GooglePlus = '/assets/images/channelicons/googlePlus.png',
    GooglePlayStore = 'assets/images/channel-logos/playstore.svg',
    AutomotiveIndia = '/assets/images/channelicons/AutomotiveIndia.svg',
    Blogs = 'assets/images/channel-logos/blog.svg',
    Booking = 'assets/images/channel-logos/blog.svg',
    ComplaintWebsites = 'assets/images/channel-logos/complaint-website.svg',
    CustomerCare = '/assets/images/channelicons/customercaretab.png',
    DiscussionForums = '/assets/images/channelicons/DiscussionForums.svg',
    ECommerceWebsites = '/assets/images/channel-logos/ecomerce.svg',
    Expedia = '/assets/images/channel-logos/expedia.svg',
    HolidayIQ = '/assets/images/channel-logos/holidayiq.svg',
    MakeMyTrip = '/assets/images/channelicons/Tweeter.svg',
    MyGov = '/assets/images/channel-logos/twitter.svg',
    News = '/assets/images/channel-logos/news-blog.svg',
    ReviewWebsites = '/assets/images/channelicons/Review Sites.svg',
    TeamBHP = '/assets/images/channel-logos/teambhp.svg',
    TripAdvisor = 'assets/images/channel-logos/tripadvisor.svg',
    Videos = '/assets/images/channelicons/Videos.svg',
    Zomato = '/assets/images/channelicons/Zomato.svg',
    Email = 'assets/images/channel-logos/email.svg',
    GoogleMyReview = '/assets/images/channelicons/GoogleMyReview.svg',
    ElectronicMedia = '/assets/images/channelicons/Electronic_Media.png',
    WhatsApp = '/assets/images/channelicons/WhatsApp.svg',
    WebsiteChatBot = '/assets/images/channelicons/WebsiteChatBot.svg',
    AppStoreReviews = '/assets/images/channelicons/AppStoreReviews.svg', 

    YouTube = '/assets/images/channelicons/Youtube.svg'
}
