import { UserRoleEnum } from 'app/core/enums/userRoleEnum';
import { ActionButton, UserMenuJson } from 'app/core/interfaces/User';
import { UserRoleDetails } from '../viewmodel/UserRoleDetails';

export interface LocobuzzUser {
    userId?: number;
    username?: string;
    password?: string;
    role?: UserRoleEnum;
    firstName?: string;
    lastName?: string;
    fullName?: string;
    emailAddress?: string;
    categoryId?: number;
    categoryName?: string;
    categoryGroupID?: string;
    categoryGroupName?: string;
    teamID?: number;
    hiddenItems?: string;
    userPersonalization?: string;
    isDisabled?: boolean;
    isDeleted?: boolean;
    managerOrAdmin?: string;
    isEnable2FAuthenticationCategoryWise?: boolean;
    typeOf2FAuthentication?: number;
    is2FAuthSetupComplete?: boolean;
    uniqueKeyFor2F?: string;
    isEnable2FAuthenticationUserWise?: boolean;
    noOfExternalLogin?: number;
    agentTicketReassignmentEnabled?: boolean;
    userAccountStatus?: string;
    isUserAssignmentDisabled?: number;
    userPasswordStatus?: string;
    menuLandingPageName?: string;
    assignmentDisabled?: number;
    skills?: number[];
    channelTypes?: number[];
    playStoreRatings?: number[];
    googleReviewRatings?: number[];
    loggedInStatus?: number;
    userMenuJson?: UserMenuJson;
    actionButton?: ActionButton;
    agentWorkFlowEnabled?: boolean;
    isCanPerformActionEnable?: boolean;
    userRole?: UserRoleDetails;
    sessionid?: string;
    token?: string;
    globalTicketVersion?: number;
}
